# GitHub Branch Protection Rules
# 这个文件是配置说明，实际的分支保护需要在GitHub仓库设置中配置

# main分支保护规则
main:
  required_status_checks:
    strict: true
    contexts:
      - ci
      - validate-docs
      - security-audit
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  restrictions: null
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false

# develop分支保护规则
develop:
  required_status_checks:
    strict: false
    contexts:
      - ci
      - validate-docs
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
  restrictions: null
  allow_force_pushes: false
  allow_deletions: false

# feature分支保护规则
feature/*:
  required_status_checks:
    strict: false
    contexts:
      - ci
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    require_code_owner_reviews: false
  restrictions:
    teams: []
    users: []
  allow_force_pushes: true
  allow_deletions: true

# bugfix分支保护规则
bugfix/*:
  required_status_checks:
    strict: false
    contexts:
      - ci
      - security-audit
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    require_code_owner_reviews: false
  restrictions: null
  allow_force_pushes: true
  allow_deletions: true

# hotfix分支保护规则
hotfix/*:
  required_status_checks:
    strict: false
    contexts:
      - ci
      - security-audit
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    require_code_owner_reviews: false
  restrictions: null
  allow_force_pushes: true
  allow_deletions: true

# release分支保护规则
release/*:
  required_status_checks:
    strict: true
    contexts:
      - ci
      - validate-docs
      - security-audit
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 2
    require_code_owner_reviews: true
  restrictions: null
  allow_force_pushes: false
  allow_deletions: false
