#!/usr/bin/env bash
set -euo pipefail

# create-github-release.sh
# Create a GitHub release with changelog and artifacts
# Usage: create-github-release.sh <version> <tag> <changelog_file>

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 <version> <tag> <changelog_file>" >&2
    exit 1
fi

VERSION="$1"
TAG="$2"
CHANGELOG_FILE="$3"

echo "🚀 Creating GitHub release: $TAG"

# Check if release already exists
if gh release view "$TAG" --repo ${{ github.repository }} >/dev/null 2>&1; then
    echo "⚠️  Release $TAG already exists, skipping creation"
    exit 0
fi

# Remove 'v' prefix from version for release title
VERSION_NO_V=${VERSION#v}

# Create release with changelog
gh release create "$TAG" \
    --title "PowerBy Skills v$VERSION_NO_V" \
    --notes-file "$CHANGELOG_FILE" \
    --draft=false \
    --prerelease=false \
    --repo ${{ github.repository }}

# Upload artifacts if they exist
if [ -d "release-assets" ]; then
    echo "📦 Uploading release assets..."
    gh release upload "$TAG" release-assets/* \
        --repo ${{ github.repository }}
fi

# Create GitHub Issue to track the release
gh issue create \
    --title "✅ Release v$VERSION Complete" \
    --body "Release v$VERSION has been successfully created and deployed.

## Release Details
- **Version**: v$VERSION
- **Tag**: $TAG
- **Release Notes**: See [CHANGELOG.md](./CHANGELOG.md)
- **Artifacts**: Available in the release

## Summary
$(cat "$CHANGELOG_FILE" | grep -A 20 "## \[v$VERSION\]" | head -25)

## Next Steps
- [ ] Review release notes
- [ ] Test released features
- [ ] Update documentation if needed
- [ ] Notify stakeholders
- [ ] Create post-release summary

## Metrics
- Total commits: $(git rev-list --count ${{ github.sha }}^..${{ github.sha }})
- Files changed: $(git diff --name-only ${{ github.sha }}^..${{ github.sha }} | wc -l)
- Lines added: $(git diff --numstat ${{ github.sha }}^..${{ github.sha }} | awk '{sum += $1} END {print sum}')
- Lines removed: $(git diff --numstat ${{ github.sha }}^..${{ github.sha }} | awk '{sum += $2} END {print sum}')

---
*Generated by GitHub Actions Workflow*"
    --label "release,completed,automation" \
    --repo ${{ github.repository }}

echo "✅ Release $TAG created successfully"
echo ""
echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/$TAG"
