#!/usr/bin/env python3
"""
update-iteration-status.py
Update iteration status based on git history and commits
Usage: update-iteration-status.py <iteration_id> <new_status>
"""

import sys
import json
import datetime
import subprocess
import os
from pathlib import Path

def get_git_commits_for_iteration(iteration_id):
    """Get commits related to a specific iteration"""
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "--grep", iteration_id, "--all"],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip().split('\n') if result.stdout.strip() else []
    except subprocess.CalledProcessError:
        return []

def update_iteration_index(iteration_id, new_status):
    """Update iteration status in the index file"""
    index_file = Path("docs/iterations/index.json")

    # Initialize iterations list
    iterations = []

    # Load existing index if it exists
    if index_file.exists():
        try:
            with open(index_file) as f:
                iterations = json.load(f)
        except json.JSONDecodeError:
            print(f"⚠️  Warning: Invalid JSON in {index_file}, creating new index")
            iterations = []

    # Find and update the iteration
    iteration_found = False
    for iteration in iterations:
        if iteration.get("id") == iteration_id:
            iteration["status"] = new_status
            iteration["updated_at"] = datetime.datetime.now().isoformat()
            iteration_found = True
            print(f"✅ Updated iteration {iteration_id} status to {new_status}")
            break

    # If iteration not found, add it
    if not iteration_found:
        iterations.append({
            "id": iteration_id,
            "status": new_status,
            "created_at": datetime.datetime.now().isoformat(),
            "updated_at": datetime.datetime.now().isoformat()
        })
        print(f"✅ Added new iteration {iteration_id} with status {new_status}")

    # Write updated index
    index_file.parent.mkdir(parents=True, exist_ok=True)
    with open(index_file, "w") as f:
        json.dump(iterations, f, indent=2)

    print(f"📄 Updated {index_file}")

def create_iteration_tracking_issue(iteration_id, status):
    """Create a GitHub issue to track iteration progress"""
    try:
        subprocess.run([
            "gh", "issue", "create",
            "--title", f"📋 Iteration {iteration_id} - Status Update: {status}",
            "--body", f"""# Iteration {iteration_id} Status Update

## Current Status
**Status**: {status}
**Updated**: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Recent Activity
{chr(10).join(get_git_commits_for_iteration(iteration_id)[:10])}

## Next Steps
- [ ] Review current progress
- [ ] Update iteration documentation
- [ ] Plan next phase

---
*Auto-generated by GitHub Actions*
""",
            "--label", f"iteration,status-{status}",
            "--repo", os.environ.get("GITHUB_REPOSITORY", "")
        ], check=True)
        print(f"✅ Created tracking issue for iteration {iteration_id}")
    except (subprocess.CalledProcessError, KeyError) as e:
        print(f"⚠️  Warning: Could not create tracking issue: {e}")

def main():
    if len(sys.argv) != 3:
        print("Usage: update-iteration-status.py <iteration_id> <status>")
        sys.exit(1)

    iteration_id = sys.argv[1]
    new_status = sys.argv[2]

    valid_statuses = ["active", "completed", "on-hold", "cancelled", "planning"]
    if new_status not in valid_statuses:
        print(f"⚠️  Warning: Status '{new_status}' not in standard statuses: {', '.join(valid_statuses)}")

    print(f"🔄 Updating iteration {iteration_id} to status: {new_status}")

    # Update iteration index
    update_iteration_index(iteration_id, new_status)

    # Create tracking issue if running in GitHub Actions
    if os.environ.get("GITHUB_ACTIONS") == "true":
        create_iteration_tracking_issue(iteration_id, new_status)

    print(f"✅ Iteration {iteration_id} update complete")

if __name__ == "__main__":
    main()
