/**
 * Start Command - 创建新分支
 */

const chalk = require('chalk');
const path = require('path');
const fs = require('fs');
const {
  BRANCH_TYPES,
  generateBranchName,
  validateBranchName
} = require('../core/branch-validator');
const { createError } = require('../core/errors');
const { branchExists, createBranch, getCurrentBranch } = require('../utils/git');

/**
 * 自动安装 Git Hooks
 * @param {string} cwd - 工作目录
 */
async function installHooks(cwd) {
  const hooksDir = path.join(cwd, '.git', 'hooks');
  const templateSource = path.join(__dirname, '..', '..', 'src', 'hooks');

  // 确保 hooks 目录存在
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // 复制 pre-commit 钩子
  const preCommitSource = path.join(templateSource, 'pre-commit.js');
  const preCommitDest = path.join(hooksDir, 'pre-commit');

  if (fs.existsSync(preCommitSource)) {
    const hookContent = `#!/usr/bin/env node
// This file is generated by powerby-git
// DO NOT EDIT MANUALLY

require('${preCommitSource.replace(/\\/g, '\\\\')}');
`;
    fs.writeFileSync(preCommitDest, hookContent);
    fs.chmodSync(preCommitDest, 0o755);
  }

  // 复制 pre-merge 钩子
  const preMergeSource = path.join(templateSource, 'pre-merge.js');
  const preMergeDest = path.join(hooksDir, 'pre-merge');

  if (fs.existsSync(preMergeSource)) {
    const hookContent = `#!/usr/bin/env node
// This file is generated by powerby-git
// DO NOT EDIT MANUALLY

require('${preMergeSource.replace(/\\/g, '\\\\')}');
`;
    fs.writeFileSync(preMergeDest, hookContent);
    fs.chmodSync(preMergeDest, 0o755);
  }
}

/**
 * 执行 start 命令
 * @param {Object} options - 命令选项
 * @param {string} options.type - 分支类型
 * @param {string} options.name - 分支名称
 * @param {string} [options.cwd] - 工作目录
 * @returns {Promise<Object>}
 */
async function executeStart(options) {
  const { type, name, cwd = process.cwd() } = options;

  // 验证类型
  if (!Object.values(BRANCH_TYPES).includes(type)) {
    throw createError('E002', `无效的分支类型: ${type}`);
  }

  // 生成完整分支名
  const branchName = generateBranchName(type, name);

  // 验证分支名
  const validation = validateBranchName(branchName, type);
  if (!validation.valid) {
    throw createError('E002', validation.errors.join(', '));
  }

  // 检查分支是否已存在
  if (await branchExists(branchName, cwd)) {
    throw createError('E001', branchName);
  }

  // 创建分支
  await createBranch(branchName, cwd);

  // 自动安装 Git Hooks
  await installHooks(cwd);

  const currentBranch = await getCurrentBranch(cwd);

  return {
    success: true,
    branchName: branchName,
    currentBranch: currentBranch,
    message: `已创建并切换到分支: ${chalk.green(branchName)}`
  };
}

/**
 * 命令配置
 */
function configureStartCommand(program) {
  program
    .command('start')
    .description('创建新的 feature 或 bugfix 分支')
    .requiredOption('--type <type>', '分支类型 (feature|bugfix|hotfix|release)')
    .requiredOption('--name <name>', '分支名称')
    .action(async (options) => {
      try {
        const result = await executeStart(options);
        console.log('\n' + chalk.green('✅ ' + result.message));
        console.log(chalk.cyan('\n🛡️  Git Hooks 已自动安装'));
        console.log(chalk.gray('   - pre-commit: 提交前检查'));
        console.log(chalk.gray('   - pre-merge: 合并前检查'));
        console.log(`\n开始开发吧！`);
      } catch (error) {
        console.error('\n' + chalk.red('❌ ' + error.message));
        if (error.hint) {
          console.error(chalk.gray('💡 ' + error.hint));
        }
        process.exit(1);
      }
    });
}

module.exports = {
  executeStart,
  configureStartCommand,
  installHooks
};
