/**
 * Git Hooks 安装脚本
 */

const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

const HOOKS_DIR = '.git/hooks';
const TEMPLATE_DIR = '.git/templates/hooks';

const HOOKS = [
  {
    name: 'pre-commit',
    source: path.join(__dirname, 'pre-commit.js'),
    description: '提交前检查文件合规性和提交信息格式'
  },
  {
    name: 'pre-merge',
    source: path.join(__dirname, 'pre-merge.js'),
    description: '合并前全量检查工作区文件合规性'
  }
];

/**
 * 安装钩子
 * @param {string} hook - 钩子名称
 * @param {string} source - 源文件路径
 * @param {string} targetDir - 目标目录
 */
function installHook(hook, source, targetDir) {
  // 确保目标目录存在
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const targetPath = path.join(targetDir, hook);

  // 检查源文件是否存在
  if (!fs.existsSync(source)) {
    console.log(chalk.red(`❌ 源文件不存在: ${source}`));
    return false;
  }

  // 创建 hook 文件
  const hookContent = `#!/usr/bin/env node
// This file is generated by powerby-git
// DO NOT EDIT MANUALLY

require('${source.replace(/\\/g, '\\\\')}');
`;

  fs.writeFileSync(targetPath, hookContent);

  // 设置执行权限
  fs.chmodSync(targetPath, 0o755);

  console.log(chalk.green(`✅ 已安装 ${hook}`));
  console.log(chalk.gray(`   ${HOOKS.find(h => h.name === hook)?.description}`));

  return true;
}

/**
 * 卸载钩子
 * @param {string} hook - 钩子名称
 * @param {string} targetDir - 目标目录
 */
function uninstallHook(hook, targetDir) {
  const targetPath = path.join(targetDir, hook);

  if (fs.existsSync(targetPath)) {
    fs.unlinkSync(targetPath);
    console.log(chalk.green(`✅ 已卸载 ${hook}`));
    return true;
  }

  console.log(chalk.gray(`⏭️  ${hook} 不存在，跳过`));
  return true;
}

/**
 * 主函数
 */
function main() {
  const args = process.argv.slice(2);
  const action = args[0] || 'install';

  console.log(chalk.cyan('\n🛡️  PowerBy Git Hooks 管理\n'));

  if (action === 'install') {
    console.log(chalk.cyan('📦 安装 Git Hooks\n'));

    // 安装到 .git/hooks
    let success = true;
    for (const hook of HOOKS) {
      if (!installHook(hook.name, hook.source, HOOKS_DIR)) {
        success = false;
      }
    }

    if (success) {
      console.log(chalk.green('\n✅ 所有 Hooks 安装成功！'));
    } else {
      console.log(chalk.red('\n❌ 部分 Hooks 安装失败'));
      process.exit(1);
    }

  } else if (action === 'uninstall') {
    console.log(chalk.cyan('🗑️  卸载 Git Hooks\n'));

    for (const hook of HOOKS) {
      uninstallHook(hook.name, HOOKS_DIR);
    }

    console.log(chalk.green('\n✅ 所有 Hooks 已卸载'));

  } else if (action === 'status') {
    console.log(chalk.cyan('📋 Hooks 状态\n'));

    for (const hook of HOOKS) {
      const targetPath = path.join(HOOKS_DIR, hook.name);
      if (fs.existsSync(targetPath)) {
        console.log(chalk.green(`✅ ${hook.name}`));
      } else {
        console.log(chalk.gray(`⏭️  ${hook.name} (未安装)`));
      }
    }

  } else {
    console.log(chalk.yellow(`\n⚠️  未知操作: ${action}`));
    console.log('用法:');
    console.log('   powerby-git-hook install   # 安装 Hooks');
    console.log('   powerby-git-hook uninstall # 卸载 Hooks');
    console.log('   powerby-git-hook status    # 查看状态');
    process.exit(1);
  }
}

module.exports = {
  installHook,
  uninstallHook,
  HOOKS
};

// 如果直接运行
if (require.main === module) {
  main();
}
